[package]
name = "caller-with-composed-component"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
wasmtime = "26.0.0"
